layout_spectrum: 0.9319149
color:
  saturation: 0
  brandStrength: 0.4957447
  lightness: 0
  brandColors:
    - '#E0E0D8'
    - '#2D322E'
    - '#212320'
    - '#7A7C79'
    - '#AFAFA7'
  rhythmicContrast: 0.2680851
typography_spectrum: 0.2808511
name: Dustincharles
