collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.2808511
color:
  saturation: 0
  brandStrength: 0.4957447
  rhythmicContrast: 0.2680851
  brandColors:
    - '#E0E0D8'
    - '#2D322E'
    - '#212320'
    - '#7A7C79'
    - '#AFAFA7'
  lightness: 0
layout_spectrum: 0.09574468
name: Dustincharles
